#!/bin/bash

PROC_SCHED=/proc/1/sched
if ! [ -f $PROC_SCHED ] || [ "$(awk 'FNR == 1 {print $1}' "$PROC_SCHED")" != "python" ]; then
    echo >&2 "Docker Container Not Detected, Exiting..."
    exit 1
fi

LOCAL_DIR="$(pwd)"
cd /home/docker/data/ShoeExpert
find . -path "\*/migrations/\*.py" -not -name "\__init__.py" -delete
find . -path "\*/migrations/\*.pyc" -delete
python manage.py makemigrations --noinput
python manage.py migrate --noinput
python manage.py collectstatic --noinput -c -l -v 0 # prereq for django-import-export
importStaticShoes
cd $LOCAL_DIR

createDockerAdminUser
