# Generated by Django 4.2 on 2023-04-15 12:46

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Running_shoes',
            fields=[
                ('arch_type', models.CharField(blank=True, choices=[('low', 'Low'), ('high', 'High')], max_length=5, null=True)),
                ('brand', models.CharField(blank=True, max_length=32, null=True)),
                ('cushioning', models.CharField(blank=True, choices=[('firm', 'Firm'), ('balanced', 'Balanced'), ('plush', 'Plush')], max_length=10, null=True)),
                ('forefoot_height', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('flexibility', models.CharField(blank=True, choices=[('rigid', 'Very stiff'), ('semi-rigid', 'Stiff'), ('balanced', 'Moderate'), ('semi-flexible', 'Flexible'), ('flexible', 'Very flexible')], max_length=24, null=True)),
                ('heel_height', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('heel_toe_drop', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pronation', models.CharField(blank=True, max_length=256, null=True)),
                ('release_date', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2024)])),
                ('strike_pattern', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('forefoot', 'Forefoot'), ('midfoot', 'Midfoot'), ('heel', 'Heel')], max_length=10), blank=True, null=True, size=None)),
                ('terrain', models.CharField(blank=True, choices=[('road', 'Road'), ('trail', 'Trail')], max_length=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('width', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('narrow', 'Narrow'), ('standard', 'Standard'), ('wide', 'Wide'), ('extra wide', 'Extra Wide')], max_length=16), blank=True, null=True, size=None)),
                ('shoe_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
    ]
