name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image on Ubuntu
      run: docker buildx install && docker build . --file Dockerfile --tag ubuntu:$(date +%s)

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image on Mac
      run: docker buildx install && docker build . --file Dockerfile --tag macos:$(date +%s)
  
  build-windows:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image on Windows
      run: docker buildx install && docker build . --file Dockerfile --tag windows:$(date +%s)

